export const qk = {
  me: ['me'] as const,
  serverInfo: ['server', 'info'] as const,
  serverMetrics: (minutes: number) => ['server', 'metrics', minutes] as const,
  events: (limit: number, siteId?: string) => ['events', limit, siteId ?? ''] as const,
  audit: (limit: number, offset: number) => ['audit', limit, offset] as const,
  sites: ['sites'] as const,
  site: (id: string) => ['sites', id] as const,
  siteMetrics: (id: string, minutes: number) => ['sites', id, 'metrics', minutes] as const,
  deployments: (id: string) => ['sites', id, 'deployments'] as const,
  certs: ['certificates'] as const,
  nodeVersions: ['node', 'versions'] as const,
  nodeAvailable: ['node', 'available'] as const,
  settings: ['settings'] as const,
  adminSettings: ['settings', 'admin'] as const,
  dnsCatalog: ['settings', 'dns-catalog'] as const,
  users: ['users'] as const,
  tokens: ['tokens'] as const,
  mail: ['mail'] as const,
  mailStatus: ['mail', 'status'] as const,
  mailQueue: (state: string) => ['mail', 'queue', state] as const,
  mimeDefaults: ['mime', 'defaults'] as const,
};
